// Generated by gencpp from file monitor_py/info.msg
// DO NOT EDIT!


#ifndef MONITOR_PY_MESSAGE_INFO_H
#define MONITOR_PY_MESSAGE_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace monitor_py
{
template <class ContainerAllocator>
struct info_
{
  typedef info_<ContainerAllocator> Type;

  info_()
    : fnum(0.0)  {
    }
  info_(const ContainerAllocator& _alloc)
    : fnum(0.0)  {
  (void)_alloc;
    }



   typedef double _fnum_type;
  _fnum_type fnum;





  typedef boost::shared_ptr< ::monitor_py::info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::monitor_py::info_<ContainerAllocator> const> ConstPtr;

}; // struct info_

typedef ::monitor_py::info_<std::allocator<void> > info;

typedef boost::shared_ptr< ::monitor_py::info > infoPtr;
typedef boost::shared_ptr< ::monitor_py::info const> infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::monitor_py::info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::monitor_py::info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace monitor_py

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'monitor_py': ['/home/pigmon/Workspace/Beiqi/gen_watcher/rospy_test/src/gen_watcher/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::monitor_py::info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::monitor_py::info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::monitor_py::info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::monitor_py::info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monitor_py::info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::monitor_py::info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::monitor_py::info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cce30792a39fb76bc5361a9e6d6ed985";
  }

  static const char* value(const ::monitor_py::info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcce30792a39fb76bULL;
  static const uint64_t static_value2 = 0xc5361a9e6d6ed985ULL;
};

template<class ContainerAllocator>
struct DataType< ::monitor_py::info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "monitor_py/info";
  }

  static const char* value(const ::monitor_py::info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::monitor_py::info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 fnum\n"
;
  }

  static const char* value(const ::monitor_py::info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::monitor_py::info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fnum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::monitor_py::info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::monitor_py::info_<ContainerAllocator>& v)
  {
    s << indent << "fnum: ";
    Printer<double>::stream(s, indent + "  ", v.fnum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MONITOR_PY_MESSAGE_INFO_H
